2025-02-06 10:48:50.491 | INFO     | __main__:decrypt_credentials:16 - -------Starting decryption and initiating the s3 client-------
2025-02-06 10:48:50.500 | INFO     | __main__:decrypt_credentials:28 - Decryption of aws credentials is successful
2025-02-06 10:51:32.697 | INFO     | __main__:decrypt_credentials:16 - -------Starting decryption and initiating the s3 client-------
2025-02-06 10:51:32.703 | INFO     | __main__:decrypt_credentials:28 - Decryption of aws credentials is successful
2025-02-06 10:51:32.703 | INFO     | __main__:get_s3_client:44 - ------Initiating s3 client------
2025-02-06 10:51:32.856 | INFO     | __main__:get_s3_client:51 - ------Successfully got the s3 client------
2025-02-06 10:52:39.506 | INFO     | __main__:decrypt_credentials:16 - -------Starting decryption and initiating the s3 client-------
2025-02-06 10:52:39.507 | ERROR    | __main__:decrypt_credentials:32 - Error decrypting the data:[Errno 2] No such file or directory: 'E:\\spark_project01\\resources\\dev\\encryptionn.key'
2025-02-06 10:52:39.507 | ERROR    | __main__:get_s3_client:55 - Error creating s3 client: Failed to get decrypted AWS credentials
2025-02-06 15:57:56.696 | INFO     | __main__:list_files_in_bucket:15 - getting the s3 client
2025-02-06 15:57:56.715 | INFO     | src.main.utility.decrypt_s3_client_object:decrypt_credentials:16 - -------Starting decryption and initiating the s3 client-------
2025-02-06 15:57:56.715 | ERROR    | src.main.utility.decrypt_s3_client_object:decrypt_credentials:32 - Error decrypting the data:[Errno 2] No such file or directory: 'E:\\spark_project01\\resources\\dev\\encryptionn.key'
2025-02-06 15:57:56.717 | ERROR    | src.main.utility.decrypt_s3_client_object:get_s3_client:55 - Error creating s3 client: Failed to get decrypted AWS credentials
2025-02-06 15:58:26.448 | INFO     | __main__:list_files_in_bucket:15 - getting the s3 client
2025-02-06 15:58:26.449 | INFO     | src.main.utility.decrypt_s3_client_object:decrypt_credentials:16 - -------Starting decryption and initiating the s3 client-------
2025-02-06 15:58:26.663 | INFO     | src.main.utility.decrypt_s3_client_object:decrypt_credentials:28 - ------Decryption of aws credentials is successful------
2025-02-06 15:58:26.664 | INFO     | src.main.utility.decrypt_s3_client_object:get_s3_client:44 - ------Initiating s3 client------
2025-02-06 15:58:26.909 | INFO     | src.main.utility.decrypt_s3_client_object:get_s3_client:51 - ------Successfully got the s3 client------
2025-02-06 16:02:53.323 | INFO     | __main__:list_files_in_bucket:15 - ------getting the s3 client------
2025-02-06 16:02:53.323 | INFO     | src.main.utility.decrypt_s3_client_object:decrypt_credentials:16 - -------Starting decryption and initiating the s3 client-------
2025-02-06 16:02:53.327 | INFO     | src.main.utility.decrypt_s3_client_object:decrypt_credentials:28 - ------Decryption of aws credentials is successful------
2025-02-06 16:02:53.327 | INFO     | src.main.utility.decrypt_s3_client_object:get_s3_client:44 - ------Initiating s3 client------
2025-02-06 16:02:53.418 | INFO     | src.main.utility.decrypt_s3_client_object:get_s3_client:51 - ------Successfully got the s3 client------
2025-02-06 16:04:35.531 | INFO     | __main__:list_files_in_bucket:15 - ------getting the s3 client------
2025-02-06 16:04:35.532 | INFO     | src.main.utility.decrypt_s3_client_object:decrypt_credentials:16 - -------Starting decryption and initiating the s3 client-------
2025-02-06 16:04:35.537 | INFO     | src.main.utility.decrypt_s3_client_object:decrypt_credentials:28 - ------Decryption of aws credentials is successful------
2025-02-06 16:04:35.537 | INFO     | src.main.utility.decrypt_s3_client_object:get_s3_client:44 - ------Initiating s3 client------
2025-02-06 16:04:35.625 | INFO     | src.main.utility.decrypt_s3_client_object:get_s3_client:51 - ------Successfully got the s3 client------
2025-02-06 16:04:37.022 | INFO     | __main__:list_files_in_bucket:27 - files in bucket: sparks3bucketproj1
2025-02-06 16:04:59.895 | INFO     | __main__:list_files_in_bucket:15 - ------getting the s3 client------
2025-02-06 16:04:59.895 | INFO     | src.main.utility.decrypt_s3_client_object:decrypt_credentials:16 - -------Starting decryption and initiating the s3 client-------
2025-02-06 16:04:59.901 | INFO     | src.main.utility.decrypt_s3_client_object:decrypt_credentials:28 - ------Decryption of aws credentials is successful------
2025-02-06 16:04:59.902 | INFO     | src.main.utility.decrypt_s3_client_object:get_s3_client:44 - ------Initiating s3 client------
2025-02-06 16:04:59.994 | INFO     | src.main.utility.decrypt_s3_client_object:get_s3_client:51 - ------Successfully got the s3 client------
2025-02-06 16:05:01.408 | INFO     | __main__:list_files_in_bucket:27 - files in bucket: sparks3bucketproj1
2025-02-06 16:06:20.542 | INFO     | __main__:list_files_in_bucket:15 - ------getting the s3 client------
2025-02-06 16:06:20.542 | INFO     | src.main.utility.decrypt_s3_client_object:decrypt_credentials:16 - -------Starting decryption and initiating the s3 client-------
2025-02-06 16:06:20.546 | INFO     | src.main.utility.decrypt_s3_client_object:decrypt_credentials:28 - ------Decryption of aws credentials is successful------
2025-02-06 16:06:20.551 | INFO     | src.main.utility.decrypt_s3_client_object:get_s3_client:44 - ------Initiating s3 client------
2025-02-06 16:06:20.640 | INFO     | src.main.utility.decrypt_s3_client_object:get_s3_client:51 - ------Successfully got the s3 client------
2025-02-06 16:06:21.983 | INFO     | __main__:list_files_in_bucket:29 - files in bucket: sparks3bucketproj1
2025-02-06 16:06:44.010 | INFO     | __main__:list_files_in_bucket:15 - ------getting the s3 client------
2025-02-06 16:06:44.010 | INFO     | src.main.utility.decrypt_s3_client_object:decrypt_credentials:16 - -------Starting decryption and initiating the s3 client-------
2025-02-06 16:06:44.014 | INFO     | src.main.utility.decrypt_s3_client_object:decrypt_credentials:28 - ------Decryption of aws credentials is successful------
2025-02-06 16:06:44.014 | INFO     | src.main.utility.decrypt_s3_client_object:get_s3_client:44 - ------Initiating s3 client------
2025-02-06 16:06:44.102 | INFO     | src.main.utility.decrypt_s3_client_object:get_s3_client:51 - ------Successfully got the s3 client------
2025-02-06 16:07:19.693 | INFO     | __main__:list_files_in_bucket:15 - ------getting the s3 client------
2025-02-06 16:07:19.693 | INFO     | src.main.utility.decrypt_s3_client_object:decrypt_credentials:16 - -------Starting decryption and initiating the s3 client-------
2025-02-06 16:07:19.697 | INFO     | src.main.utility.decrypt_s3_client_object:decrypt_credentials:28 - ------Decryption of aws credentials is successful------
2025-02-06 16:07:19.697 | INFO     | src.main.utility.decrypt_s3_client_object:get_s3_client:44 - ------Initiating s3 client------
2025-02-06 16:07:19.776 | INFO     | src.main.utility.decrypt_s3_client_object:get_s3_client:51 - ------Successfully got the s3 client------
2025-02-06 16:07:21.155 | ERROR    | __main__:list_files_in_bucket:36 - An error occurred (NoSuchBucket) when calling the ListObjectsV2 operation: The specified bucket does not exist
2025-02-07 13:17:57.749 | INFO     | src.main.read.list_s3_files:list_files_in_bucket:15 - ------getting the s3 client------
2025-02-07 13:17:57.783 | INFO     | src.main.utility.decrypt_s3_client_object:decrypt_credentials:16 - -------Starting decryption and initiating the s3 client-------
2025-02-07 13:17:57.865 | INFO     | src.main.utility.decrypt_s3_client_object:decrypt_credentials:28 - ------Decryption of aws credentials is successful------
2025-02-07 13:17:57.866 | INFO     | src.main.utility.decrypt_s3_client_object:get_s3_client:44 - ------Initiating s3 client------
2025-02-07 13:17:57.966 | INFO     | src.main.utility.decrypt_s3_client_object:get_s3_client:51 - ------Successfully got the s3 client------
2025-02-07 13:17:59.544 | ERROR    | src.main.read.list_s3_files:list_files_in_bucket:36 - An error occurred (NoSuchBucket) when calling the ListObjectsV2 operation: The specified bucket does not exist
2025-02-07 13:18:51.249 | INFO     | src.main.read.list_s3_files:list_files_in_bucket:15 - ------getting the s3 client------
2025-02-07 13:18:51.249 | INFO     | src.main.utility.decrypt_s3_client_object:decrypt_credentials:16 - -------Starting decryption and initiating the s3 client-------
2025-02-07 13:18:51.252 | INFO     | src.main.utility.decrypt_s3_client_object:decrypt_credentials:28 - ------Decryption of aws credentials is successful------
2025-02-07 13:18:51.253 | INFO     | src.main.utility.decrypt_s3_client_object:get_s3_client:44 - ------Initiating s3 client------
2025-02-07 13:18:51.333 | INFO     | src.main.utility.decrypt_s3_client_object:get_s3_client:51 - ------Successfully got the s3 client------
2025-02-07 13:18:52.692 | ERROR    | src.main.read.list_s3_files:list_files_in_bucket:37 - An error occurred (NoSuchBucket) when calling the ListObjectsV2 operation: The specified bucket does not exist
2025-02-07 13:19:35.813 | INFO     | src.main.read.list_s3_files:list_files_in_bucket:15 - ------getting the s3 client------
2025-02-07 13:19:35.813 | INFO     | src.main.utility.decrypt_s3_client_object:decrypt_credentials:16 - -------Starting decryption and initiating the s3 client-------
2025-02-07 13:19:35.817 | INFO     | src.main.utility.decrypt_s3_client_object:decrypt_credentials:28 - ------Decryption of aws credentials is successful------
2025-02-07 13:19:35.817 | INFO     | src.main.utility.decrypt_s3_client_object:get_s3_client:44 - ------Initiating s3 client------
2025-02-07 13:19:35.909 | INFO     | src.main.utility.decrypt_s3_client_object:get_s3_client:51 - ------Successfully got the s3 client------
2025-02-07 14:12:53.565 | INFO     | __main__:list_files:25 - ------ Getting the list of files------
2025-02-07 14:16:03.710 | INFO     | src.main.utility.decrypt_s3_client_object:decrypt_credentials:16 - -------Starting decryption and initiating the s3 client-------
2025-02-07 14:16:03.713 | INFO     | src.main.utility.decrypt_s3_client_object:decrypt_credentials:28 - ------Decryption of aws credentials is successful------
2025-02-07 14:16:03.714 | INFO     | src.main.utility.decrypt_s3_client_object:get_s3_client:44 - ------Initiating s3 client------
2025-02-07 14:16:03.844 | INFO     | src.main.utility.decrypt_s3_client_object:get_s3_client:51 - ------Successfully got the s3 client------
2025-02-07 14:17:16.072 | INFO     | src.main.utility.decrypt_s3_client_object:decrypt_credentials:16 - -------Starting decryption and initiating the s3 client-------
2025-02-07 14:17:16.078 | INFO     | src.main.utility.decrypt_s3_client_object:decrypt_credentials:28 - ------Decryption of aws credentials is successful------
2025-02-07 14:17:16.078 | INFO     | src.main.utility.decrypt_s3_client_object:get_s3_client:44 - ------Initiating s3 client------
2025-02-07 14:17:16.211 | INFO     | src.main.utility.decrypt_s3_client_object:get_s3_client:51 - ------Successfully got the s3 client------
2025-02-07 14:18:08.510 | INFO     | src.main.utility.decrypt_s3_client_object:decrypt_credentials:16 - -------Starting decryption and initiating the s3 client-------
2025-02-07 14:18:08.520 | INFO     | src.main.utility.decrypt_s3_client_object:decrypt_credentials:28 - ------Decryption of aws credentials is successful------
2025-02-07 14:18:08.521 | INFO     | src.main.utility.decrypt_s3_client_object:get_s3_client:44 - ------Initiating s3 client------
2025-02-07 14:18:08.731 | INFO     | src.main.utility.decrypt_s3_client_object:get_s3_client:51 - ------Successfully got the s3 client------
2025-02-07 14:20:15.306 | INFO     | src.main.utility.decrypt_s3_client_object:decrypt_credentials:16 - -------Starting decryption and initiating the s3 client-------
2025-02-07 14:20:15.313 | INFO     | src.main.utility.decrypt_s3_client_object:decrypt_credentials:28 - ------Decryption of aws credentials is successful------
2025-02-07 14:20:15.313 | INFO     | src.main.utility.decrypt_s3_client_object:get_s3_client:44 - ------Initiating s3 client------
2025-02-07 14:20:15.440 | INFO     | src.main.utility.decrypt_s3_client_object:get_s3_client:51 - ------Successfully got the s3 client------
2025-02-07 14:20:15.990 | INFO     | __main__:list_files:26 - ------ Getting the list of files------
2025-02-07 14:20:17.610 | INFO     | __main__:list_files:34 - ------files fetched successfully------
2025-02-07 15:41:38.915 | INFO     | src.main.utility.decrypt_s3_client_object:decrypt_credentials:16 - -------Starting decryption and initiating the s3 client-------
2025-02-07 15:41:39.004 | INFO     | src.main.utility.decrypt_s3_client_object:decrypt_credentials:28 - ------Decryption of aws credentials is successful------
2025-02-07 15:41:39.005 | INFO     | src.main.utility.decrypt_s3_client_object:get_s3_client:44 - ------Initiating s3 client------
2025-02-07 15:41:39.098 | INFO     | src.main.utility.decrypt_s3_client_object:get_s3_client:51 - ------Successfully got the s3 client------
2025-02-07 15:43:39.729 | INFO     | src.main.utility.decrypt_s3_client_object:decrypt_credentials:16 - -------Starting decryption and initiating the s3 client-------
2025-02-07 15:43:39.732 | INFO     | src.main.utility.decrypt_s3_client_object:decrypt_credentials:28 - ------Decryption of aws credentials is successful------
2025-02-07 15:43:39.733 | INFO     | src.main.utility.decrypt_s3_client_object:get_s3_client:44 - ------Initiating s3 client------
2025-02-07 15:43:39.821 | INFO     | src.main.utility.decrypt_s3_client_object:get_s3_client:51 - ------Successfully got the s3 client------
2025-02-07 15:43:40.095 | INFO     | __main__:download_files:53 - ------Starting the files download
2025-02-07 15:43:40.095 | ERROR    | __main__:download_files:62 - An error occurred during file download: GetFiles.list_files() takes 1 positional argument but 2 were given
2025-02-07 15:44:37.430 | INFO     | src.main.utility.decrypt_s3_client_object:decrypt_credentials:16 - -------Starting decryption and initiating the s3 client-------
2025-02-07 15:44:37.433 | INFO     | src.main.utility.decrypt_s3_client_object:decrypt_credentials:28 - ------Decryption of aws credentials is successful------
2025-02-07 15:44:37.434 | INFO     | src.main.utility.decrypt_s3_client_object:get_s3_client:44 - ------Initiating s3 client------
2025-02-07 15:44:37.521 | INFO     | src.main.utility.decrypt_s3_client_object:get_s3_client:51 - ------Successfully got the s3 client------
2025-02-07 15:44:37.752 | INFO     | __main__:download_files:53 - ------Starting the files download
2025-02-07 15:44:37.752 | INFO     | __main__:list_files:28 - ------ Getting the list of files------
2025-02-07 15:44:38.947 | INFO     | __main__:list_files:34 - ------files fetched successfully------
2025-02-07 15:44:39.397 | INFO     | __main__:download_files:59 - ------Files downloaded successfully------
2025-02-07 15:57:05.332 | INFO     | src.main.utility.decrypt_s3_client_object:decrypt_credentials:16 - -------Starting decryption and initiating the s3 client-------
2025-02-07 15:57:05.334 | INFO     | src.main.utility.decrypt_s3_client_object:decrypt_credentials:28 - ------Decryption of aws credentials is successful------
2025-02-07 15:57:05.335 | INFO     | src.main.utility.decrypt_s3_client_object:get_s3_client:44 - ------Initiating s3 client------
2025-02-07 15:57:05.399 | INFO     | src.main.utility.decrypt_s3_client_object:get_s3_client:51 - ------Successfully got the s3 client------
2025-02-07 15:57:19.443 | INFO     | src.main.utility.decrypt_s3_client_object:decrypt_credentials:16 - -------Starting decryption and initiating the s3 client-------
2025-02-07 15:57:19.445 | INFO     | src.main.utility.decrypt_s3_client_object:decrypt_credentials:28 - ------Decryption of aws credentials is successful------
2025-02-07 15:57:19.446 | INFO     | src.main.utility.decrypt_s3_client_object:get_s3_client:44 - ------Initiating s3 client------
2025-02-07 15:57:19.496 | INFO     | src.main.utility.decrypt_s3_client_object:get_s3_client:51 - ------Successfully got the s3 client------
2025-02-07 15:57:19.638 | INFO     | __main__:download_files:53 - ------Starting the files download------
2025-02-07 15:57:19.638 | INFO     | __main__:list_files:28 - ------ Getting the list of files------
2025-02-07 15:57:20.951 | INFO     | __main__:download_files:62 - ------Files downloaded successfully and saved to E:\spark_project01\files\raw_files and size is 1.3134610652923584------
2025-02-07 16:16:42.887 | INFO     | src.main.utility.decrypt_s3_client_object:decrypt_credentials:16 - -------Starting decryption and initiating the s3 client-------
2025-02-07 16:16:42.890 | INFO     | src.main.utility.decrypt_s3_client_object:decrypt_credentials:28 - ------Decryption of aws credentials is successful------
2025-02-07 16:16:42.890 | INFO     | src.main.utility.decrypt_s3_client_object:get_s3_client:44 - ------Initiating s3 client------
2025-02-07 16:16:42.962 | INFO     | src.main.utility.decrypt_s3_client_object:get_s3_client:51 - ------Successfully got the s3 client------
2025-02-07 16:16:43.104 | INFO     | __main__:download_files:54 - ------ Starting the files download ------
2025-02-07 16:16:43.105 | INFO     | __main__:list_files:29 - ------ Getting the list of files ------
2025-02-07 16:16:44.454 | INFO     | __main__:download_files:63 - ------ Files downloaded successfully and saved to E:\spark_project01\files\raw_files and size is 1.3498342037200928 ------
2025-03-13 11:25:12.683 | INFO     | __main__:list_files_in_bucket:15 - ------getting the s3 client------
2025-03-13 11:25:12.702 | INFO     | src.main.utility.decrypt_s3_client_object:decrypt_credentials:16 - -------Starting decryption and initiating the s3 client-------
2025-03-13 11:25:12.706 | INFO     | src.main.utility.decrypt_s3_client_object:decrypt_credentials:28 - ------Decryption of aws credentials is successful------
2025-03-13 11:25:12.707 | INFO     | src.main.utility.decrypt_s3_client_object:get_s3_client:44 - ------Initiating s3 client------
2025-03-13 11:25:12.741 | INFO     | src.main.utility.decrypt_s3_client_object:get_s3_client:51 - ------Successfully got the s3 client------
2025-03-13 11:25:13.720 | ERROR    | __main__:list_files_in_bucket:37 - An error occurred (NoSuchBucket) when calling the ListObjectsV2 operation: The specified bucket does not exist
2025-03-13 11:25:41.884 | INFO     | __main__:list_files_in_bucket:15 - ------getting the s3 client------
2025-03-13 11:25:41.885 | INFO     | src.main.utility.decrypt_s3_client_object:decrypt_credentials:16 - -------Starting decryption and initiating the s3 client-------
2025-03-13 11:25:41.890 | INFO     | src.main.utility.decrypt_s3_client_object:decrypt_credentials:28 - ------Decryption of aws credentials is successful------
2025-03-13 11:25:41.891 | INFO     | src.main.utility.decrypt_s3_client_object:get_s3_client:44 - ------Initiating s3 client------
2025-03-13 11:25:41.948 | INFO     | src.main.utility.decrypt_s3_client_object:get_s3_client:51 - ------Successfully got the s3 client------
2025-03-13 11:26:17.793 | INFO     | __main__:list_files_in_bucket:15 - ------getting the s3 client------
2025-03-13 11:26:17.794 | INFO     | src.main.utility.decrypt_s3_client_object:decrypt_credentials:16 - -------Starting decryption and initiating the s3 client-------
2025-03-13 11:26:17.800 | INFO     | src.main.utility.decrypt_s3_client_object:decrypt_credentials:28 - ------Decryption of aws credentials is successful------
2025-03-13 11:26:17.800 | INFO     | src.main.utility.decrypt_s3_client_object:get_s3_client:44 - ------Initiating s3 client------
2025-03-13 11:26:17.835 | INFO     | src.main.utility.decrypt_s3_client_object:get_s3_client:51 - ------Successfully got the s3 client------
2025-03-13 11:27:56.441 | INFO     | src.main.utility.decrypt_s3_client_object:decrypt_credentials:16 - -------Starting decryption and initiating the s3 client-------
2025-03-13 11:27:56.445 | INFO     | src.main.utility.decrypt_s3_client_object:decrypt_credentials:28 - ------Decryption of aws credentials is successful------
2025-03-13 11:27:56.445 | INFO     | src.main.utility.decrypt_s3_client_object:get_s3_client:44 - ------Initiating s3 client------
2025-03-13 11:27:56.484 | INFO     | src.main.utility.decrypt_s3_client_object:get_s3_client:51 - ------Successfully got the s3 client------
2025-03-13 11:29:29.841 | INFO     | src.main.utility.decrypt_s3_client_object:decrypt_credentials:16 - -------Starting decryption and initiating the s3 client-------
2025-03-13 11:29:29.845 | INFO     | src.main.utility.decrypt_s3_client_object:decrypt_credentials:28 - ------Decryption of aws credentials is successful------
2025-03-13 11:29:29.845 | INFO     | src.main.utility.decrypt_s3_client_object:get_s3_client:44 - ------Initiating s3 client------
2025-03-13 11:29:29.882 | INFO     | src.main.utility.decrypt_s3_client_object:get_s3_client:51 - ------Successfully got the s3 client------
2025-03-13 11:29:30.892 | ERROR    | __main__:upload_to_s3:31 - ------ Error occurred while uploading the file to S3: Need to rewind the stream <botocore.httpchecksum.AwsChunkedWrapper object at 0x0000014D36117E90>, but stream is not seekable. ------
2025-03-13 11:31:31.139 | INFO     | src.main.utility.decrypt_s3_client_object:decrypt_credentials:16 - -------Starting decryption and initiating the s3 client-------
2025-03-13 11:31:31.143 | INFO     | src.main.utility.decrypt_s3_client_object:decrypt_credentials:28 - ------Decryption of aws credentials is successful------
2025-03-13 11:31:31.143 | INFO     | src.main.utility.decrypt_s3_client_object:get_s3_client:44 - ------Initiating s3 client------
2025-03-13 11:31:31.179 | INFO     | src.main.utility.decrypt_s3_client_object:get_s3_client:51 - ------Successfully got the s3 client------
2025-03-13 11:31:32.165 | ERROR    | __main__:upload_to_s3:31 - ------ Error occurred while uploading the file to S3: Failed to upload E:/spark_project01/files/transformed_data/parquet/part-00000-ed1c252d-c7ea-4d8b-9c5b-a9f28844dc78-c000.snappy.parquet to sparks3bucketprojj1/transformed_data/part-00000-ed1c252d-c7ea-4d8b-9c5b-a9f28844dc78-c000.snappy.parquet: An error occurred (NoSuchBucket) when calling the PutObject operation: The specified bucket does not exist ------
2025-03-13 11:34:01.733 | INFO     | src.main.utility.decrypt_s3_client_object:decrypt_credentials:16 - -------Starting decryption and initiating the s3 client-------
2025-03-13 11:34:01.733 | INFO     | src.main.utility.decrypt_s3_client_object:decrypt_credentials:28 - ------Decryption of aws credentials is successful------
2025-03-13 11:34:01.733 | INFO     | src.main.utility.decrypt_s3_client_object:get_s3_client:44 - ------Initiating s3 client------
2025-03-13 11:34:01.779 | INFO     | src.main.utility.decrypt_s3_client_object:get_s3_client:51 - ------Successfully got the s3 client------
