2025-02-06 15:57:56.696 | INFO     | __main__:list_files_in_bucket:15 - getting the s3 client
2025-02-06 15:57:56.715 | INFO     | src.main.utility.decrypt_s3_client_object:decrypt_credentials:16 - -------Starting decryption and initiating the s3 client-------
2025-02-06 15:57:56.715 | ERROR    | src.main.utility.decrypt_s3_client_object:decrypt_credentials:32 - Error decrypting the data:[Errno 2] No such file or directory: 'E:\\spark_project01\\resources\\dev\\encryptionn.key'
2025-02-06 15:57:56.717 | ERROR    | src.main.utility.decrypt_s3_client_object:get_s3_client:55 - Error creating s3 client: Failed to get decrypted AWS credentials
2025-02-06 15:58:26.448 | INFO     | __main__:list_files_in_bucket:15 - getting the s3 client
2025-02-06 15:58:26.449 | INFO     | src.main.utility.decrypt_s3_client_object:decrypt_credentials:16 - -------Starting decryption and initiating the s3 client-------
2025-02-06 15:58:26.663 | INFO     | src.main.utility.decrypt_s3_client_object:decrypt_credentials:28 - ------Decryption of aws credentials is successful------
2025-02-06 15:58:26.664 | INFO     | src.main.utility.decrypt_s3_client_object:get_s3_client:44 - ------Initiating s3 client------
2025-02-06 15:58:26.909 | INFO     | src.main.utility.decrypt_s3_client_object:get_s3_client:51 - ------Successfully got the s3 client------
2025-02-06 16:02:53.323 | INFO     | __main__:list_files_in_bucket:15 - ------getting the s3 client------
2025-02-06 16:02:53.323 | INFO     | src.main.utility.decrypt_s3_client_object:decrypt_credentials:16 - -------Starting decryption and initiating the s3 client-------
2025-02-06 16:02:53.327 | INFO     | src.main.utility.decrypt_s3_client_object:decrypt_credentials:28 - ------Decryption of aws credentials is successful------
2025-02-06 16:02:53.327 | INFO     | src.main.utility.decrypt_s3_client_object:get_s3_client:44 - ------Initiating s3 client------
2025-02-06 16:02:53.418 | INFO     | src.main.utility.decrypt_s3_client_object:get_s3_client:51 - ------Successfully got the s3 client------
2025-02-06 16:04:35.531 | INFO     | __main__:list_files_in_bucket:15 - ------getting the s3 client------
2025-02-06 16:04:35.532 | INFO     | src.main.utility.decrypt_s3_client_object:decrypt_credentials:16 - -------Starting decryption and initiating the s3 client-------
2025-02-06 16:04:35.537 | INFO     | src.main.utility.decrypt_s3_client_object:decrypt_credentials:28 - ------Decryption of aws credentials is successful------
2025-02-06 16:04:35.537 | INFO     | src.main.utility.decrypt_s3_client_object:get_s3_client:44 - ------Initiating s3 client------
2025-02-06 16:04:35.625 | INFO     | src.main.utility.decrypt_s3_client_object:get_s3_client:51 - ------Successfully got the s3 client------
2025-02-06 16:04:37.022 | INFO     | __main__:list_files_in_bucket:27 - files in bucket: sparks3bucketproj1
2025-02-06 16:04:59.895 | INFO     | __main__:list_files_in_bucket:15 - ------getting the s3 client------
2025-02-06 16:04:59.895 | INFO     | src.main.utility.decrypt_s3_client_object:decrypt_credentials:16 - -------Starting decryption and initiating the s3 client-------
2025-02-06 16:04:59.901 | INFO     | src.main.utility.decrypt_s3_client_object:decrypt_credentials:28 - ------Decryption of aws credentials is successful------
2025-02-06 16:04:59.902 | INFO     | src.main.utility.decrypt_s3_client_object:get_s3_client:44 - ------Initiating s3 client------
2025-02-06 16:04:59.994 | INFO     | src.main.utility.decrypt_s3_client_object:get_s3_client:51 - ------Successfully got the s3 client------
2025-02-06 16:05:01.408 | INFO     | __main__:list_files_in_bucket:27 - files in bucket: sparks3bucketproj1
2025-02-06 16:06:20.542 | INFO     | __main__:list_files_in_bucket:15 - ------getting the s3 client------
2025-02-06 16:06:20.542 | INFO     | src.main.utility.decrypt_s3_client_object:decrypt_credentials:16 - -------Starting decryption and initiating the s3 client-------
2025-02-06 16:06:20.546 | INFO     | src.main.utility.decrypt_s3_client_object:decrypt_credentials:28 - ------Decryption of aws credentials is successful------
2025-02-06 16:06:20.551 | INFO     | src.main.utility.decrypt_s3_client_object:get_s3_client:44 - ------Initiating s3 client------
2025-02-06 16:06:20.640 | INFO     | src.main.utility.decrypt_s3_client_object:get_s3_client:51 - ------Successfully got the s3 client------
2025-02-06 16:06:21.983 | INFO     | __main__:list_files_in_bucket:29 - files in bucket: sparks3bucketproj1
2025-02-06 16:06:44.010 | INFO     | __main__:list_files_in_bucket:15 - ------getting the s3 client------
2025-02-06 16:06:44.010 | INFO     | src.main.utility.decrypt_s3_client_object:decrypt_credentials:16 - -------Starting decryption and initiating the s3 client-------
2025-02-06 16:06:44.014 | INFO     | src.main.utility.decrypt_s3_client_object:decrypt_credentials:28 - ------Decryption of aws credentials is successful------
2025-02-06 16:06:44.014 | INFO     | src.main.utility.decrypt_s3_client_object:get_s3_client:44 - ------Initiating s3 client------
2025-02-06 16:06:44.102 | INFO     | src.main.utility.decrypt_s3_client_object:get_s3_client:51 - ------Successfully got the s3 client------
2025-02-06 16:07:19.693 | INFO     | __main__:list_files_in_bucket:15 - ------getting the s3 client------
2025-02-06 16:07:19.693 | INFO     | src.main.utility.decrypt_s3_client_object:decrypt_credentials:16 - -------Starting decryption and initiating the s3 client-------
2025-02-06 16:07:19.697 | INFO     | src.main.utility.decrypt_s3_client_object:decrypt_credentials:28 - ------Decryption of aws credentials is successful------
2025-02-06 16:07:19.697 | INFO     | src.main.utility.decrypt_s3_client_object:get_s3_client:44 - ------Initiating s3 client------
2025-02-06 16:07:19.776 | INFO     | src.main.utility.decrypt_s3_client_object:get_s3_client:51 - ------Successfully got the s3 client------
2025-02-06 16:07:21.155 | ERROR    | __main__:list_files_in_bucket:36 - An error occurred (NoSuchBucket) when calling the ListObjectsV2 operation: The specified bucket does not exist
2025-02-07 13:17:57.749 | INFO     | src.main.read.list_s3_files:list_files_in_bucket:15 - ------getting the s3 client------
2025-02-07 13:17:57.783 | INFO     | src.main.utility.decrypt_s3_client_object:decrypt_credentials:16 - -------Starting decryption and initiating the s3 client-------
2025-02-07 13:17:57.865 | INFO     | src.main.utility.decrypt_s3_client_object:decrypt_credentials:28 - ------Decryption of aws credentials is successful------
2025-02-07 13:17:57.866 | INFO     | src.main.utility.decrypt_s3_client_object:get_s3_client:44 - ------Initiating s3 client------
2025-02-07 13:17:57.966 | INFO     | src.main.utility.decrypt_s3_client_object:get_s3_client:51 - ------Successfully got the s3 client------
2025-02-07 13:17:59.544 | ERROR    | src.main.read.list_s3_files:list_files_in_bucket:36 - An error occurred (NoSuchBucket) when calling the ListObjectsV2 operation: The specified bucket does not exist
2025-02-07 13:18:51.249 | INFO     | src.main.read.list_s3_files:list_files_in_bucket:15 - ------getting the s3 client------
2025-02-07 13:18:51.249 | INFO     | src.main.utility.decrypt_s3_client_object:decrypt_credentials:16 - -------Starting decryption and initiating the s3 client-------
2025-02-07 13:18:51.252 | INFO     | src.main.utility.decrypt_s3_client_object:decrypt_credentials:28 - ------Decryption of aws credentials is successful------
2025-02-07 13:18:51.253 | INFO     | src.main.utility.decrypt_s3_client_object:get_s3_client:44 - ------Initiating s3 client------
2025-02-07 13:18:51.333 | INFO     | src.main.utility.decrypt_s3_client_object:get_s3_client:51 - ------Successfully got the s3 client------
2025-02-07 13:18:52.692 | ERROR    | src.main.read.list_s3_files:list_files_in_bucket:37 - An error occurred (NoSuchBucket) when calling the ListObjectsV2 operation: The specified bucket does not exist
2025-02-07 13:19:35.813 | INFO     | src.main.read.list_s3_files:list_files_in_bucket:15 - ------getting the s3 client------
2025-02-07 13:19:35.813 | INFO     | src.main.utility.decrypt_s3_client_object:decrypt_credentials:16 - -------Starting decryption and initiating the s3 client-------
2025-02-07 13:19:35.817 | INFO     | src.main.utility.decrypt_s3_client_object:decrypt_credentials:28 - ------Decryption of aws credentials is successful------
2025-02-07 13:19:35.817 | INFO     | src.main.utility.decrypt_s3_client_object:get_s3_client:44 - ------Initiating s3 client------
2025-02-07 13:19:35.909 | INFO     | src.main.utility.decrypt_s3_client_object:get_s3_client:51 - ------Successfully got the s3 client------
2025-03-13 11:25:12.683 | INFO     | __main__:list_files_in_bucket:15 - ------getting the s3 client------
2025-03-13 11:25:12.702 | INFO     | src.main.utility.decrypt_s3_client_object:decrypt_credentials:16 - -------Starting decryption and initiating the s3 client-------
2025-03-13 11:25:12.706 | INFO     | src.main.utility.decrypt_s3_client_object:decrypt_credentials:28 - ------Decryption of aws credentials is successful------
2025-03-13 11:25:12.707 | INFO     | src.main.utility.decrypt_s3_client_object:get_s3_client:44 - ------Initiating s3 client------
2025-03-13 11:25:12.741 | INFO     | src.main.utility.decrypt_s3_client_object:get_s3_client:51 - ------Successfully got the s3 client------
2025-03-13 11:25:13.720 | ERROR    | __main__:list_files_in_bucket:37 - An error occurred (NoSuchBucket) when calling the ListObjectsV2 operation: The specified bucket does not exist
2025-03-13 11:25:41.884 | INFO     | __main__:list_files_in_bucket:15 - ------getting the s3 client------
2025-03-13 11:25:41.885 | INFO     | src.main.utility.decrypt_s3_client_object:decrypt_credentials:16 - -------Starting decryption and initiating the s3 client-------
2025-03-13 11:25:41.890 | INFO     | src.main.utility.decrypt_s3_client_object:decrypt_credentials:28 - ------Decryption of aws credentials is successful------
2025-03-13 11:25:41.891 | INFO     | src.main.utility.decrypt_s3_client_object:get_s3_client:44 - ------Initiating s3 client------
2025-03-13 11:25:41.948 | INFO     | src.main.utility.decrypt_s3_client_object:get_s3_client:51 - ------Successfully got the s3 client------
2025-03-13 11:26:17.793 | INFO     | __main__:list_files_in_bucket:15 - ------getting the s3 client------
2025-03-13 11:26:17.794 | INFO     | src.main.utility.decrypt_s3_client_object:decrypt_credentials:16 - -------Starting decryption and initiating the s3 client-------
2025-03-13 11:26:17.800 | INFO     | src.main.utility.decrypt_s3_client_object:decrypt_credentials:28 - ------Decryption of aws credentials is successful------
2025-03-13 11:26:17.800 | INFO     | src.main.utility.decrypt_s3_client_object:get_s3_client:44 - ------Initiating s3 client------
2025-03-13 11:26:17.835 | INFO     | src.main.utility.decrypt_s3_client_object:get_s3_client:51 - ------Successfully got the s3 client------
