2025-02-06 15:57:56.696 | INFO     | __main__:list_files_in_bucket:15 - getting the s3 client
2025-02-06 15:57:56.715 | INFO     | src.main.utility.decrypt_s3_client_object:decrypt_credentials:16 - -------Starting decryption and initiating the s3 client-------
2025-02-06 15:57:56.715 | ERROR    | src.main.utility.decrypt_s3_client_object:decrypt_credentials:32 - Error decrypting the data:[Errno 2] No such file or directory: 'E:\\spark_project01\\resources\\dev\\encryptionn.key'
2025-02-06 15:57:56.717 | ERROR    | src.main.utility.decrypt_s3_client_object:get_s3_client:55 - Error creating s3 client: Failed to get decrypted AWS credentials
2025-02-06 15:58:26.448 | INFO     | __main__:list_files_in_bucket:15 - getting the s3 client
2025-02-06 15:58:26.449 | INFO     | src.main.utility.decrypt_s3_client_object:decrypt_credentials:16 - -------Starting decryption and initiating the s3 client-------
2025-02-06 15:58:26.663 | INFO     | src.main.utility.decrypt_s3_client_object:decrypt_credentials:28 - ------Decryption of aws credentials is successful------
2025-02-06 15:58:26.664 | INFO     | src.main.utility.decrypt_s3_client_object:get_s3_client:44 - ------Initiating s3 client------
2025-02-06 15:58:26.909 | INFO     | src.main.utility.decrypt_s3_client_object:get_s3_client:51 - ------Successfully got the s3 client------
2025-02-06 16:02:53.323 | INFO     | __main__:list_files_in_bucket:15 - ------getting the s3 client------
2025-02-06 16:02:53.323 | INFO     | src.main.utility.decrypt_s3_client_object:decrypt_credentials:16 - -------Starting decryption and initiating the s3 client-------
2025-02-06 16:02:53.327 | INFO     | src.main.utility.decrypt_s3_client_object:decrypt_credentials:28 - ------Decryption of aws credentials is successful------
2025-02-06 16:02:53.327 | INFO     | src.main.utility.decrypt_s3_client_object:get_s3_client:44 - ------Initiating s3 client------
2025-02-06 16:02:53.418 | INFO     | src.main.utility.decrypt_s3_client_object:get_s3_client:51 - ------Successfully got the s3 client------
2025-02-06 16:04:35.531 | INFO     | __main__:list_files_in_bucket:15 - ------getting the s3 client------
2025-02-06 16:04:35.532 | INFO     | src.main.utility.decrypt_s3_client_object:decrypt_credentials:16 - -------Starting decryption and initiating the s3 client-------
2025-02-06 16:04:35.537 | INFO     | src.main.utility.decrypt_s3_client_object:decrypt_credentials:28 - ------Decryption of aws credentials is successful------
2025-02-06 16:04:35.537 | INFO     | src.main.utility.decrypt_s3_client_object:get_s3_client:44 - ------Initiating s3 client------
2025-02-06 16:04:35.625 | INFO     | src.main.utility.decrypt_s3_client_object:get_s3_client:51 - ------Successfully got the s3 client------
2025-02-06 16:04:37.022 | INFO     | __main__:list_files_in_bucket:27 - files in bucket: sparks3bucketproj1
2025-02-06 16:04:59.895 | INFO     | __main__:list_files_in_bucket:15 - ------getting the s3 client------
2025-02-06 16:04:59.895 | INFO     | src.main.utility.decrypt_s3_client_object:decrypt_credentials:16 - -------Starting decryption and initiating the s3 client-------
2025-02-06 16:04:59.901 | INFO     | src.main.utility.decrypt_s3_client_object:decrypt_credentials:28 - ------Decryption of aws credentials is successful------
2025-02-06 16:04:59.902 | INFO     | src.main.utility.decrypt_s3_client_object:get_s3_client:44 - ------Initiating s3 client------
2025-02-06 16:04:59.994 | INFO     | src.main.utility.decrypt_s3_client_object:get_s3_client:51 - ------Successfully got the s3 client------
2025-02-06 16:05:01.408 | INFO     | __main__:list_files_in_bucket:27 - files in bucket: sparks3bucketproj1
2025-02-06 16:06:20.542 | INFO     | __main__:list_files_in_bucket:15 - ------getting the s3 client------
2025-02-06 16:06:20.542 | INFO     | src.main.utility.decrypt_s3_client_object:decrypt_credentials:16 - -------Starting decryption and initiating the s3 client-------
2025-02-06 16:06:20.546 | INFO     | src.main.utility.decrypt_s3_client_object:decrypt_credentials:28 - ------Decryption of aws credentials is successful------
2025-02-06 16:06:20.551 | INFO     | src.main.utility.decrypt_s3_client_object:get_s3_client:44 - ------Initiating s3 client------
2025-02-06 16:06:20.640 | INFO     | src.main.utility.decrypt_s3_client_object:get_s3_client:51 - ------Successfully got the s3 client------
2025-02-06 16:06:21.983 | INFO     | __main__:list_files_in_bucket:29 - files in bucket: sparks3bucketproj1
2025-02-06 16:06:44.010 | INFO     | __main__:list_files_in_bucket:15 - ------getting the s3 client------
2025-02-06 16:06:44.010 | INFO     | src.main.utility.decrypt_s3_client_object:decrypt_credentials:16 - -------Starting decryption and initiating the s3 client-------
2025-02-06 16:06:44.014 | INFO     | src.main.utility.decrypt_s3_client_object:decrypt_credentials:28 - ------Decryption of aws credentials is successful------
2025-02-06 16:06:44.014 | INFO     | src.main.utility.decrypt_s3_client_object:get_s3_client:44 - ------Initiating s3 client------
2025-02-06 16:06:44.102 | INFO     | src.main.utility.decrypt_s3_client_object:get_s3_client:51 - ------Successfully got the s3 client------
2025-02-06 16:07:19.693 | INFO     | __main__:list_files_in_bucket:15 - ------getting the s3 client------
2025-02-06 16:07:19.693 | INFO     | src.main.utility.decrypt_s3_client_object:decrypt_credentials:16 - -------Starting decryption and initiating the s3 client-------
2025-02-06 16:07:19.697 | INFO     | src.main.utility.decrypt_s3_client_object:decrypt_credentials:28 - ------Decryption of aws credentials is successful------
2025-02-06 16:07:19.697 | INFO     | src.main.utility.decrypt_s3_client_object:get_s3_client:44 - ------Initiating s3 client------
2025-02-06 16:07:19.776 | INFO     | src.main.utility.decrypt_s3_client_object:get_s3_client:51 - ------Successfully got the s3 client------
2025-02-06 16:07:21.155 | ERROR    | __main__:list_files_in_bucket:36 - An error occurred (NoSuchBucket) when calling the ListObjectsV2 operation: The specified bucket does not exist
